### ISSUE TITLE
Wish: Accompanying cmdline tool that posts a jekyll markdown post to G+

### ISSUE THREAD

**Issue by brainstorm** [jmmv/markdown2social#1]
Usecase: Post those to G+ automatically as I pu(bli)sh them:

https://github.com/brainstorm/brainstorm.github.io/tree/master/_posts/blog

PD: And why not, to FB and TW too, via a git hook script :P

**Comment by jmmv** [comment]
There are many things in this request that are worth pursuing:
1. The ability to support Jekyll files as input—that is, parse Front Matter and use the right title for the post.
2. The ability to directly push to Google+ without the copy/paste dance.
3. The addition of support for Facebook (formatting, if any, and push).
4. The addition of support for TW (?).
5. The ability to trigger this behavior from a Git hook script.

Can you please file one individual bug for each and close this one? I'd do it myself, but then you would not get notified of any updates...

**Comment by brainstorm** [comment]
Nice try at outsourcing boring stuff ;P

I will follow/subscribe to them when and if they are available :)

**Comment by jmmv** [comment]
Done for the ones I care about: #6 and #7.
